name: s3l_torch
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cmake=4.0.3
  - freexl=2.0.0
  - gdal=3.11.3
  - geos=3.14.0
  - giflib=5.2.2
  - icu=75.1
  - json-c=0.18
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libarchive=3.8.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal-core=3.11.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.2.0
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - libkml=1.3.0
  - libkrb5=1.21.3
  - liblapack=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.53
  - librttopo=1.1.0
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.38.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.10.0
  - lzo=2.10
  - minizip=4.0.10
  - muparser=2.3.5
  - ncurses=6.5
  - openssl=3.6.0
  - pcre2=10.46
  - pip=25.0
  - proj=9.6.2
  - python=3.9.23
  - python_abi=3.9
  - readline=8.2
  - rhash=1.4.6
  - setuptools=75.8.0
  - snappy=1.2.2
  - sqlite=3.50.4
  - tk=8.6.13
  - uriparser=0.9.8
  - wheel=0.45.1
  - xerces-c=3.2.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.1.0
      - accelerate==1.7.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argcomplete==3.6.2
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - asyncer==0.0.8
      - attrs==25.3.0
      - babel==2.17.0
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blinker==1.9.0
      - boto3==1.38.39
      - botocore==1.38.39
      - certifi==2025.4.26
      - cffi==1.17.1
      - chamfer==2.0.0
      - charset-normalizer==3.4.2
      - click==8.1.8
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.0
      - cryptography==45.0.4
      - cubic-feature-sampling==1.1.0
      - cycler==0.12.1
      - cyclonedds==0.10.5
      - dash==3.0.4
      - dataclasses-json==0.6.7
      - datasets==3.6.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - diff-gaussian-rasterization==0.0.0
      - diff-gaussian-rasterization-depth==0.0.0
      - diff-surfel-rasterization==0.0.1
      - dill==0.3.8
      - easydict==1.13
      - einops==0.8.1
      - emd==0.0.0
      - entrypoints==0.4
      - eval-type-backport==0.2.2
      - evo==1.11.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.115.13
      - fastjsonschema==2.21.1
      - ffmpy==0.6.0
      - filelock==3.17.0
      - filetype==1.2.0
      - flask==3.0.3
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fpsample==0.3.3
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.2.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.9.0
      - gradio==4.26.0
      - gradio-client==0.15.1
      - gridding==2.1.0
      - gridding-distance==1.0.0
      - grpcio==1.70.0
      - h11==0.16.0
      - h5py==3.13.0
      - hatchling==1.27.0
      - hf-xet==1.1.4
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - humanfriendly==10.0
      - icecream==2.1.4
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - imgviz==1.7.5
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iopath==0.1.11
      - ipycanvas==0.13.3
      - ipyevents==2.0.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - jmespath==1.0.1
      - joblib==1.5.0
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kaolin==0.17.0
      - kiwisolver==1.4.7
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lietorch==0.3
      - lightning-utilities==0.14.3
      - llvmlite==0.43.0
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - megfile==4.1.8
      - mistune==3.1.3
      - mmcv==1.6.0
      - mpmath==1.3.0
      - multidict==6.5.0
      - multiprocess==0.70.16
      - munch==4.0.0
      - mypy-extensions==1.1.0
      - narwhals==1.39.0
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - notebook==7.4.3
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnx==1.18.0
      - onnxruntime==1.19.2
      - onnxruntime-gpu==1.19.2
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optimum==1.26.1
      - orjson==3.10.18
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - paramiko==3.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - pipdeptree==2.28.0
      - platformdirs==4.3.6
      - plotly==6.0.1
      - pluggy==1.6.0
      - plyfile==1.1.2
      - pointnet2-ops==3.0.0
      - pooch==1.8.2
      - portalocker==3.1.1
      - prefetch-generator==1.0.3
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pulp==3.2.1
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pybind11==2.13.6
      - pycocotools==2.0.10
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydicom==2.4.4
      - pydub==0.25.1
      - pyglm==2.8.2
      - pygltflib==1.16.4
      - pygments==2.19.1
      - pymatting==1.1.14
      - pymcubes==0.1.6
      - pynacl==1.5.0
      - pyopengl==3.1.9
      - pyopengl-accelerate==3.1.9
      - pyparsing==3.2.1
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytorch-msssim==1.0.0
      - pytorch3d==0.7.8
      - pytz==2025.2
      - pyvista==0.45.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - regex==2024.11.6
      - rembg==2.0.61
      - requests==2.32.3
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rich-click==1.8.9
      - rpds-py==0.24.0
      - ruff==0.12.0
      - s3transfer==0.13.0
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - scooby==0.10.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - simple-knn==0.0.0
      - six==1.17.0
      - slangtorch==1.3.7
      - smmap==5.0.2
      - sniffio==1.3.1
      - socksio==1.0.0
      - soupsieve==2.7
      - speedtest-cli==2.1.3
      - stack-data==0.6.3
      - starlette==0.46.2
      - supervision==0.25.1
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==3.0.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==1.0.19
      - tinycss2==1.4.0
      - tinycudann==1.6
      - tokenizers==0.21.1
      - tomli==2.2.1
      - tomlkit==0.12.0
      - torch==2.6.0+cu124
      - torch-cluster==1.6.3
      - torchaudio==2.6.0+cu124
      - torchmetrics==1.7.2
      - torchvision==0.21.0+cu124
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformations==2024.5.24
      - transformers==4.52.4
      - transforms3d==0.4.2
      - trimesh==4.6.12
      - triton==3.2.0
      - trove-classifiers==2025.5.9.12
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==1.26.20
      - usd-core==25.5
      - uvicorn==0.34.3
      - vtk==9.4.2
      - wandb==0.20.1
      - warp-lang==1.7.1
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==11.0.3
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.20.1
      - zipp==3.21.0
